spring:
  application:
    name: territory-backend

  datasource:
    url: ${SUPABASE_URL}
    username: ${SUPABASE_USER}
    password: ${SUPABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          format_sql: true
    show-sql: false

server:
  port: 8080