spring:
  application:
    name: territory-backend

  datasource:
    url: ${{ secrets.SUPABASE_URL }}
    username: ${{ secrets.SUPABASE_USERNAME }}
    password: ${{ secrets.SUPABASE_PASSWORD }}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: false

server:
  port: 8080